//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Gexx2DPaperTanks;

namespace Gexx2DPaperTanks
{
	public struct TanksTree
	{

	}

	/// <summary>
	/// Описание танка
	/// </summary>
	public class Tank
	{
		public string Model;		//	Модель танка
		public float HitPoints;		//	Хитов
		public float Width;			//	Ширина
		public float Length;		//	Длинна
	}
}

